; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Nastavení rychlosti sériového monitoru (musí se shodovat s Serial.begin v kódu)
monitor_speed = 115200

; Volitelné: Rychlost nahrávání (upload speed). 921600 je obvykle bezpečné maximum pro ESP32
upload_speed = 921600

; Zde se přidávají externí knihovny. Příklad:
; lib_deps =
;     bblanchon/ArduinoJson @ ^6.21.3
;     adafruit/DHT sensor library @ ^1.4.4
lib_deps =
    tzapu/WiFiManager @ ^2.0.17
